### ISSUE TITLE
Could you share codes, please.

### ISSUE THREAD

**Issue by kk2487** [FuyaLuo/PearlGAN#2]
I have read your paper and feel very interested.
Could you share codes? 

thanks.

**Comment by FuyaLuo** [comment]
> I have read your paper and feel very interested. Could you share codes?
> 
> thanks.

**Comment by FuyaLuo** [comment]
Thank you for your interest. We will make the code available as soon as the paper is published.

**Comment by FuyaLuo** [comment]
> I have read your paper and feel very interested. Could you share codes?
> 
> thanks.

Thank you for your interest. We will make the code available as soon as the paper is published.
