### ISSUE TITLE
About edge_map

### ISSUE THREAD

**Issue by HaHaFish1014** [FuyaLuo/PearlGAN#7]
Thank you for your great work!
I want to know if you can release some code or scripts to get the edge maps of Nighttime TIR images and daytime color images.

**Comment by FuyaLuo** [comment]
> Thank you for your great work! I want to know if you can release some code or scripts to get the edge maps of Nighttime TIR images and daytime color images.

The code for extracting the edges of NTIR image using MCI method can be downloaded through Baidu cloud link.
![CodeDownload](https://github.com/user-attachments/assets/e12298aa-2b22-4e6f-94da-6a515ce41afe)

And the Matlab code for extracting DC image using Canny edges is:
Vis_edge = edge(rgb2gray(Vis_img), 'canny', [0.1, 0.2]);

**Comment by HaHaFish1014** [comment]
> > Thank you for your great work! I want to know if you can release some code or scripts to get the edge maps of Nighttime TIR images and daytime color images.
> 
> The code for extracting the edges of NTIR image using MCI method can be downloaded through Baidu cloud link. ![CodeDownload](https://private-user-images.githubusercontent.com/26736293/362262710-e12298aa-2b22-4e6f-94da-6a515ce41afe.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMzEyNjEsIm5iZiI6MTcyNTMzMDk2MSwicGF0aCI6Ii8yNjczNjI5My8zNjIyNjI3MTAtZTEyMjk4YWEtMmIyMi00ZTZmLTk0ZGEtNmE1MTVjZTQxYWZlLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDAyMzYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4Zjc0ZTc5MjY2OTg1ZTAzZWMxYWM5ZjExMWFiMjViZmViYjNlNTU4YTQ1ZGQ3NTg1ZTMxZDY4MmNiMTg5N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LHcFg2NEpWZ3gj3JeKe6YGIf_TrytMsW1CK3nrFxV0Y)
> 
> And the Matlab code for extracting DC image using Canny edges is: Vis_edge = edge(rgb2gray(Vis_img), 'canny', [0.1, 0.2]);

Thank you for your prompt reply!
